### ISSUE TITLE
Library not loaded: /usr/local/lib/libkytea.0.dylib in version = "0.1.5"

### ISSUE THREAD

**Issue by hurutoriya** [chezou/Mykytea-python#17]
Thanks for providing pypi package for Kytea 😄 

I make a one issues for visibility.

## Context

I installed kytea package via pip and poetry and I face to `Library not loaded: /usr/local/lib/libkytea.0.dylib` error.

### pip

```bash
import Mykytea
../../../../.pyenv/versions/3.7.9/lib/python3.7/site-packages/Mykytea.py:15: in <module>
    import _Mykytea
E   ImportError: dlopen(/Users/shunya.ueta/.pyenv/versions/3.7.9/lib/python3.7/site-packages/_Mykytea.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/lib/libkytea.0.dylib
E     Referenced from: /Users/shunya.ueta/.pyenv/versions/3.7.9/lib/python3.7/site-packages/_Mykytea.cpython-37m-darwin.so
E     Reason: image not found
```
### poetry

```bash
% cat pyproject.toml
[tool.poetry]
name = "kytea-test"
version = "0.1.0"
description = ""
authors = ["Shunya UETA' <shunyaueta01@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
kytea = "~=0.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

`poetry.lock`

> [[package]]
> name = "kytea"
> version = "0.1.5"

<details>
<summary>poetry.lock raw</summary>
<pre>
<code>
% cat pyproject.toml
[tool.poetry]
name = "kytea-test"
version = "0.1.0"
description = ""
authors = ["Shunya UETA' <shunyaueta01@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
kytea = "~=0.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
shunya.ueta@LF2101010013 kytea-test % poetry add kytea=1.15

  ValueError

  Could not find a matching version of package kytea

  at ~/.poetry/lib/poetry/console/commands/init.py:368 in _find_best_version_for_package
      364│
      365│         if not package:
      366│             # TODO: find similar
      367│             raise ValueError(
    → 368│                 "Could not find a matching version of package {}".format(name)
      369│             )
      370│
      371│         return package.pretty_name, selector.find_recommended_require_version(package)
      372│
shunya.ueta@LF2101010013 kytea-test % poetry add kytea==1.15

  ValueError

  Could not find a matching version of package kytea

  at ~/.poetry/lib/poetry/console/commands/init.py:368 in _find_best_version_for_package
      364│
      365│         if not package:
      366│             # TODO: find similar
      367│             raise ValueError(
    → 368│                 "Could not find a matching version of package {}".format(name)
      369│             )
      370│
      371│         return package.pretty_name, selector.find_recommended_require_version(package)
      372│
shunya.ueta@LF2101010013 kytea-test % poetry add kytea
The following packages are already present in the pyproject.toml and will be skipped:

  • kytea

If you want to update it to the latest compatible version, you can use `poetry update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`.

Nothing to add.
shunya.ueta@LF2101010013 kytea-test % poetry update kytea
Updating dependencies
Resolving dependencies... (0.1s)

No dependencies to install or update
shunya.ueta@LF2101010013 kytea-test % cat pyproject.toml
[tool.poetry]
name = "kytea-test"
version = "0.1.0"
description = ""
authors = ["Shunya UETA' <shunyaueta01@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
kytea = "~=0.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
shunya.ueta@LF2101010013 kytea-test % cat poetry.lock
[[package]]
name = "atomicwrites"
version = "1.4.0"
description = "Atomic file writes."
category = "dev"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"

[[package]]
name = "attrs"
version = "20.3.0"
description = "Classes Without Boilerplate"
category = "dev"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"

[package.extras]
dev = ["coverage[toml] (>=5.0.2)", "hypothesis", "pympler", "pytest (>=4.3.0)", "six", "zope.interface", "furo", "sphinx", "pre-commit"]
docs = ["furo", "sphinx", "zope.interface"]
tests = ["coverage[toml] (>=5.0.2)", "hypothesis", "pympler", "pytest (>=4.3.0)", "six", "zope.interface"]
tests_no_zope = ["coverage[toml] (>=5.0.2)", "hypothesis", "pympler", "pytest (>=4.3.0)", "six"]

[[package]]
name = "colorama"
version = "0.4.4"
description = "Cross-platform colored terminal text."
category = "dev"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"

[[package]]
name = "importlib-metadata"
version = "4.0.1"
description = "Read metadata from Python packages"
category = "dev"
optional = false
python-versions = ">=3.6"

[package.dependencies]
typing-extensions = {version = ">=3.6.4", markers = "python_version < \"3.8\""}
zipp = ">=0.5"

[package.extras]
docs = ["sphinx", "jaraco.packaging (>=8.2)", "rst.linker (>=1.9)"]
testing = ["pytest (>=4.6)", "pytest-checkdocs (>=2.4)", "pytest-flake8", "pytest-cov", "pytest-enabler (>=1.0.1)", "packaging", "pep517", "pyfakefs", "flufl.flake8", "pytest-black (>=0.3.7)", "pytest-mypy", "importlib-resources (>=1.3)"]

[[package]]
name = "kytea"
version = "0.1.5"
description = "An text analysis toolkit KyTea binding"
category = "main"
optional = false
python-versions = "*"

[[package]]
name = "more-itertools"
version = "8.7.0"
description = "More routines for operating on iterables, beyond itertools"
category = "dev"
optional = false
python-versions = ">=3.5"

[[package]]
name = "packaging"
version = "20.9"
description = "Core utilities for Python packages"
category = "dev"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"

[package.dependencies]
pyparsing = ">=2.0.2"

[[package]]
name = "pluggy"
version = "0.13.1"
description = "plugin and hook calling mechanisms for python"
category = "dev"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"

[package.dependencies]
importlib-metadata = {version = ">=0.12", markers = "python_version < \"3.8\""}

[package.extras]
dev = ["pre-commit", "tox"]

[[package]]
name = "py"
version = "1.10.0"
description = "library with cross-python path, ini-parsing, io, code, log facilities"
category = "dev"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"

[[package]]
name = "pyparsing"
version = "2.4.7"
description = "Python parsing module"
category = "dev"
optional = false
python-versions = ">=2.6, !=3.0.*, !=3.1.*, !=3.2.*"

[[package]]
name = "pytest"
version = "5.4.3"
description = "pytest: simple powerful testing with Python"
category = "dev"
optional = false
python-versions = ">=3.5"

[package.dependencies]
atomicwrites = {version = ">=1.0", markers = "sys_platform == \"win32\""}
attrs = ">=17.4.0"
colorama = {version = "*", markers = "sys_platform == \"win32\""}
importlib-metadata = {version = ">=0.12", markers = "python_version < \"3.8\""}
more-itertools = ">=4.0.0"
packaging = "*"
pluggy = ">=0.12,<1.0"
py = ">=1.5.0"
wcwidth = "*"

[package.extras]
checkqa-mypy = ["mypy (==v0.761)"]
testing = ["argcomplete", "hypothesis (>=3.56)", "mock", "nose", "requests", "xmlschema"]

[[package]]
name = "typing-extensions"
version = "3.10.0.0"
description = "Backported and Experimental Type Hints for Python 3.5+"
category = "dev"
optional = false
python-versions = "*"

[[package]]
name = "wcwidth"
version = "0.2.5"
description = "Measures the displayed width of unicode strings in a terminal"
category = "dev"
optional = false
python-versions = "*"

[[package]]
name = "zipp"
version = "3.4.1"
description = "Backport of pathlib-compatible object wrapper for zip files"
category = "dev"
optional = false
python-versions = ">=3.6"

[package.extras]
docs = ["sphinx", "jaraco.packaging (>=8.2)", "rst.linker (>=1.9)"]
testing = ["pytest (>=4.6)", "pytest-checkdocs (>=1.2.3)", "pytest-flake8", "pytest-cov", "pytest-enabler", "jaraco.itertools", "func-timeout", "pytest-black (>=0.3.7)", "pytest-mypy"]

[metadata]
lock-version = "1.1"
python-versions = "^3.7"
content-hash = "b44d6e26ab208fd2b945cb0327f07d71388ee4de26faa394114a141cc1d7622f"

[metadata.files]
atomicwrites = [
    {file = "atomicwrites-1.4.0-py2.py3-none-any.whl", hash = "sha256:6d1784dea7c0c8d4a5172b6c620f40b6e4cbfdf96d783691f2e1302a7b88e197"},
    {file = "atomicwrites-1.4.0.tar.gz", hash = "sha256:ae70396ad1a434f9c7046fd2dd196fc04b12f9e91ffb859164193be8b6168a7a"},
]
attrs = [
    {file = "attrs-20.3.0-py2.py3-none-any.whl", hash = "sha256:31b2eced602aa8423c2aea9c76a724617ed67cf9513173fd3a4f03e3a929c7e6"},
    {file = "attrs-20.3.0.tar.gz", hash = "sha256:832aa3cde19744e49938b91fea06d69ecb9e649c93ba974535d08ad92164f700"},
]
colorama = [
    {file = "colorama-0.4.4-py2.py3-none-any.whl", hash = "sha256:9f47eda37229f68eee03b24b9748937c7dc3868f906e8ba69fbcbdd3bc5dc3e2"},
    {file = "colorama-0.4.4.tar.gz", hash = "sha256:5941b2b48a20143d2267e95b1c2a7603ce057ee39fd88e7329b0c292aa16869b"},
]
importlib-metadata = [
    {file = "importlib_metadata-4.0.1-py3-none-any.whl", hash = "sha256:d7eb1dea6d6a6086f8be21784cc9e3bcfa55872b52309bc5fad53a8ea444465d"},
    {file = "importlib_metadata-4.0.1.tar.gz", hash = "sha256:8c501196e49fb9df5df43833bdb1e4328f64847763ec8a50703148b73784d581"},
]
kytea = [
    {file = "kytea-0.1.5-cp35-cp35m-macosx_10_13_x86_64.whl", hash = "sha256:f910b4d573ffe88d0ae0748f966ccc7150565dfe67f8f54472b88bd6475b10ce"},
    {file = "kytea-0.1.5-cp35-cp35m-manylinux2010_x86_64.whl", hash = "sha256:7a31190fc7ccdc1ce164ec3c7fc71110ba2768a6080e3cc6ad138ed332892ce8"},
    {file = "kytea-0.1.5-cp35-cp35m-win32.whl", hash = "sha256:432da7ed9f877e9fc6ca3963fb05bdd7bfe4624c22aa17ab9738e384964b2b7e"},
    {file = "kytea-0.1.5-cp35-cp35m-win_amd64.whl", hash = "sha256:5cc439a2037143912d0e3a5cc4960d53e79610299c72016f775c9cf4b8eaeef4"},
    {file = "kytea-0.1.5-cp36-cp36m-macosx_10_13_x86_64.whl", hash = "sha256:b342f1712235b5a8bf994b6a8b89fdaa2894493dd8cc2c193ff208c5fb24a47a"},
    {file = "kytea-0.1.5-cp36-cp36m-manylinux2010_x86_64.whl", hash = "sha256:4a7fc3f0067b82cfe56cd48ea93472e964cbc62e6cce74f488c6021369eab891"},
    {file = "kytea-0.1.5-cp36-cp36m-win32.whl", hash = "sha256:27e2f39133d55359df6d1f3da6da15b48b480bf41fb080bb9f464cd7ea335453"},
    {file = "kytea-0.1.5-cp36-cp36m-win_amd64.whl", hash = "sha256:e154bee9cc464946b658488835a7c2ec67bec6c71ab614a71fdc69bb94b4a248"},
    {file = "kytea-0.1.5-cp37-cp37m-macosx_10_13_x86_64.whl", hash = "sha256:ab3713993e4167d2446400319c2865d0b21c8b99463ec0a9682dea346877b450"},
    {file = "kytea-0.1.5-cp37-cp37m-manylinux2010_x86_64.whl", hash = "sha256:c0d3598506f1318e4d3cbd61c799ef3f4dd511b006a382b7e95ca536eb707d25"},
    {file = "kytea-0.1.5-cp37-cp37m-win32.whl", hash = "sha256:117bc8d09d3636e28c297f6a49d808cdd3f6712c1bf40316bcb4c711b5714c70"},
    {file = "kytea-0.1.5-cp37-cp37m-win_amd64.whl", hash = "sha256:2ffe40e85fdf2dfe37bec71d987681c2a1589807168d8f85d7eec0083da14fe6"},
    {file = "kytea-0.1.5-cp38-cp38-macosx_10_13_x86_64.whl", hash = "sha256:1955c77e185dee53b33e1603f24fa57041f67dc1dc2c941b36a0f9b65b1f7d52"},
    {file = "kytea-0.1.5-cp38-cp38-manylinux2010_x86_64.whl", hash = "sha256:ee260ada4226884902e455e429574f9f8e15372a6c3238ea5f2d46d588687a1b"},
    {file = "kytea-0.1.5-cp38-cp38-win32.whl", hash = "sha256:456c3cf23bd921be58f7cf9986a2ef1e7422316c5c24b72d630d6db0b8f8fd5e"},
    {file = "kytea-0.1.5-cp38-cp38-win_amd64.whl", hash = "sha256:b1b87039d588964eb300ff9b1ceeeb8f5177a8bfabd0a0e45a23562e4a0cb1da"},
    {file = "kytea-0.1.5-py3.5-macosx-10.13-x86_64.egg", hash = "sha256:d288612b4df2668ce83c90f1b3f8d954a859e04c4096683d6891e50ecf8d70d3"},
    {file = "kytea-0.1.5-py3.6-macosx-10.13-x86_64.egg", hash = "sha256:48afb2742c346ce6bb017844e133ae86821b7ffce6750a1581a2fd7fddcb1eed"},
    {file = "kytea-0.1.5-py3.7-macosx-10.13-x86_64.egg", hash = "sha256:3064088785647801b8c463dd5c8f81511eca39ad102e53a1fe1c5c4b51f146de"},
    {file = "kytea-0.1.5-py3.8-macosx-10.13-x86_64.egg", hash = "sha256:fcc928f5c57b6c1079fd053187db29281a8c2b68d25d64210e76e6a71e028c5f"},
    {file = "kytea-0.1.5.tar.gz", hash = "sha256:52b5adcf7d85d0537aaff19d8f23c823c726e09504f0b9b7c5e15bcdf4a90f74"},
]
more-itertools = [
    {file = "more-itertools-8.7.0.tar.gz", hash = "sha256:c5d6da9ca3ff65220c3bfd2a8db06d698f05d4d2b9be57e1deb2be5a45019713"},
    {file = "more_itertools-8.7.0-py3-none-any.whl", hash = "sha256:5652a9ac72209ed7df8d9c15daf4e1aa0e3d2ccd3c87f8265a0673cd9cbc9ced"},
]
packaging = [
    {file = "packaging-20.9-py2.py3-none-any.whl", hash = "sha256:67714da7f7bc052e064859c05c595155bd1ee9f69f76557e21f051443c20947a"},
    {file = "packaging-20.9.tar.gz", hash = "sha256:5b327ac1320dc863dca72f4514ecc086f31186744b84a230374cc1fd776feae5"},
]
pluggy = [
    {file = "pluggy-0.13.1-py2.py3-none-any.whl", hash = "sha256:966c145cd83c96502c3c3868f50408687b38434af77734af1e9ca461a4081d2d"},
    {file = "pluggy-0.13.1.tar.gz", hash = "sha256:15b2acde666561e1298d71b523007ed7364de07029219b604cf808bfa1c765b0"},
]
py = [
    {file = "py-1.10.0-py2.py3-none-any.whl", hash = "sha256:3b80836aa6d1feeaa108e046da6423ab8f6ceda6468545ae8d02d9d58d18818a"},
    {file = "py-1.10.0.tar.gz", hash = "sha256:21b81bda15b66ef5e1a777a21c4dcd9c20ad3efd0b3f817e7a809035269e1bd3"},
]
pyparsing = [
    {file = "pyparsing-2.4.7-py2.py3-none-any.whl", hash = "sha256:ef9d7589ef3c200abe66653d3f1ab1033c3c419ae9b9bdb1240a85b024efc88b"},
    {file = "pyparsing-2.4.7.tar.gz", hash = "sha256:c203ec8783bf771a155b207279b9bccb8dea02d8f0c9e5f8ead507bc3246ecc1"},
]
pytest = [
    {file = "pytest-5.4.3-py3-none-any.whl", hash = "sha256:5c0db86b698e8f170ba4582a492248919255fcd4c79b1ee64ace34301fb589a1"},
    {file = "pytest-5.4.3.tar.gz", hash = "sha256:7979331bfcba207414f5e1263b5a0f8f521d0f457318836a7355531ed1a4c7d8"},
]
typing-extensions = [
    {file = "typing_extensions-3.10.0.0-py2-none-any.whl", hash = "sha256:0ac0f89795dd19de6b97debb0c6af1c70987fd80a2d62d1958f7e56fcc31b497"},
    {file = "typing_extensions-3.10.0.0-py3-none-any.whl", hash = "sha256:779383f6086d90c99ae41cf0ff39aac8a7937a9283ce0a414e5dd782f4c94a84"},
    {file = "typing_extensions-3.10.0.0.tar.gz", hash = "sha256:50b6f157849174217d0656f99dc82fe932884fb250826c18350e159ec6cdf342"},
]
wcwidth = [
    {file = "wcwidth-0.2.5-py2.py3-none-any.whl", hash = "sha256:beb4802a9cebb9144e99086eff703a642a13d6a0052920003a230f3294bbe784"},
    {file = "wcwidth-0.2.5.tar.gz", hash = "sha256:c4d647b99872929fdb7bdcaa4fbe7f01413ed3d98077df798530e5b04f116c83"},
]
zipp = [
    {file = "zipp-3.4.1-py3-none-any.whl", hash = "sha256:51cb66cc54621609dd593d1787f286ee42a5c0adbb4b29abea5a63edc3e03098"},
    {file = "zipp-3.4.1.tar.gz", hash = "sha256:3607921face881ba3e026887d8150cca609d517579abe052ac81fc5aeffdbd76"},
]
</code>
</pre>
</details>

```bash
% poetry run python -c "import Mykytea"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/shunya.ueta/Library/Caches/pypoetry/virtualenvs/kytea-test-rk2eubxs-py3.7/lib/python3.7/site-packages/Mykytea.py", line 15, in <module>
    import _Mykytea
ImportError: dlopen(/Users/shunya.ueta/Library/Caches/pypoetry/virtualenvs/kytea-test-rk2eubxs-py3.7/lib/python3.7/site-packages/_Mykytea.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/lib/libkytea.0.dylib
  Referenced from: /Users/shunya.ueta/Library/Caches/pypoetry/virtualenvs/kytea-test-rk2eubxs-py3.7/lib/python3.7/site-packages/_Mykytea.cpython-37m-darwin.so
  Reason: image not found
```

## My env

```bash
% python -V 
Python 3.7.9

% which python
/Users/shunya.ueta/.pyenv/shims/python
```

**Comment by chezou** [comment]
Good point.

Mykytea wheel assumes that kytea is installed under `/usr/local/lib`, while your kytea exists another place.

This should be Mykytea issue and there are two options we can avoid it like:

1. Use [`delocate`](https://pypi.org/project/delocate/), like Linux's `audit-wheel` https://realpython.com/python-wheels/
2. Install from source using wheel instead.

@hurutoriya  Currently, I don't have enough time to approach for option 1, so could you try option 2? Or, PR would be welcome :)

**Comment by hurutoriya** [comment]
@chezou 
Thanks for a good suggestion. I will try it later. 😄

**Comment by hurutoriya** [comment]
@chezou 
I tried  building `kytea`  at locally then `poetry run python -c "import Mykytea"` is working.
Sorry for lack of knowledge about `dylib` mechanism. 
As a note, share the simple make command to build keytea ant test kytea command,

```makefile
.PHONY: keytea-install
keytea-install: ## install and build kytea
	curl -SsL -o kytea.tar.gz http://www.phontron.com/kytea/download/kytea-0.4.7.tar.gz
	mkdir -p /tmp/kytea
	tar -xzvf kytea.tar.gz -C /tmp/kytea --strip-components 1
	cd /tmp/kytea && ./configure && make -j4 && make install
	rm kytea.tar.gz

.PHONY: kytea-test
kytea-test: ## check kytea lib installed by C++ source code build
	echo "山田太郎はコーヒーを買って飲んだ。" | kytea
	poetry run python -c "import Mykytea"
```

**Comment by chezou** [comment]
JFYI, 0.1.6 would avoid this issue https://pypi.org/project/kytea/0.1.6/
