### ISSUE TITLE
_config->getModelFile()が-modelで指定した値と異なるデフォルト値を返す

### ISSUE THREAD

**Issue by nishio** [chezou/Mykytea-python#2]
パラメータに-modelオプションを指定した場合にsplit_argvの直後ではconfigに確かにその内容が入っているが、
_config->parseRunCommandLine(len, configs);の直後の状態で _config->getModelFile().c_str() は "/usr/local/share/kytea/model.bin" を返す。

https://github.com/chezou/Mykytea-python/blob/master/mykytea.cpp#L25

またおそらくそれが原因で、自作のモデルをKyTeaに読ませようと考えて-modelに指定した場合もデフォルトのモデルが読まれてしまう。

## 再現手段

再現スクリプト

    # t.py
    import os
    import Mykytea
    modelfile = "/home/nishio/yagokoro/my_kytea_active/work/000.mod"
    assert os.path.isfile(modelfile)
    opt = "-model %s" % modelfile
    mykytea = Mykytea.Mykytea(opt)

GDB

    $ gdb python
    (gdb) b mykytea.cpp:30
    No symbol table is loaded.  Use the "file" command.
    Make breakpoint pending on future shared library load? (y or [n]) y
    Breakpoint 1 (mykytea.cpp:30) pending.
    (gdb) b mykytea.cpp:32
    No symbol table is loaded.  Use the "file" command.
    Make breakpoint pending on future shared library load? (y or [n]) y
    Breakpoint 2 (mykytea.cpp:32) pending.
    (gdb) run t.py
    Starting program: /usr/bin/python t.py
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

    Breakpoint 1, Mykytea::Mykytea (this=0x9b0ad0, str=<optimized out>) at mykytea.cpp:30
    30        KyteaConfig* _config = new KyteaConfig();
    (gdb) print configs[1]
    $1 = 0x7ffff7e829bb "/home/nishio/yagokoro/my_kytea_active/work/000.mod"
    (gdb) c
    Continuing.

    Breakpoint 2, Mykytea::Mykytea (this=0x9b0ad0, str=<optimized out>) at mykytea.cpp:32
    32        config = _config;
    (gdb) print _config->getModelFile().c_str()
    $2 = 0x9f2258 "/usr/local/share/kytea/model.bin"
    (gdb) n
    34        Kytea* _kytea = new Kytea(_config);
    (gdb) n
    35        _kytea->readModel(_config->getModelFile().c_str());
    (gdb) print _config->getModelFile().c_str()
    $3 = 0x9f2258 "/usr/local/share/kytea/model.bin"

30行目の時点でconfigsに入っていたモデルのパスが、32行目の時点で_config->getModelFile().c_str()では返らずデフォルトのパスが返り、35行目でそのデフォルトのパスが_kytea->readModelに渡されていることがわかる。

**Comment by chezou** [comment]
https://github.com/chezou/Mykytea-python/commit/299ede443043a157681461034c939894243cc708 で修正しました。

原因は`parseRunCommandLine(argc, argv)`の`argv`がコマンドライン引数を想定しており、argv[0]にファイル名を入れるという仕様が理解できていなかったためのバグでした。
