### ISSUE TITLE
ImportError: dlopen(/Users/myname/Library/Python/3.8/lib/python/site-packages/_Mykytea.cpython-38-darwin.so, 2): Symbol not found: __ZN5kytea10StringUtil9normalizeERKNS_11KyteaString

### ISSUE THREAD

**Issue by lechang-zhang** [chezou/Mykytea-python#26]
Thank you for providing Mykytea-python :)

I installed Mykytea-python via pip, 
`pip install kytea`

And then wrote the code below to use the basic functionality of kytea
```
import Mykytea

opt = "-model /opt/homebrew/Cellar/kytea/0.4.7/share/kytea/model.bin"
mk = Mykytea.Mykytea(opt)
s = "今日はいい天気です"

for word in mk.getWS(s):
   print(word)

print(mk.getTagsToString(s))

t = mk.getTags(s)
showTags(t)

tt = mk.getAllTags(s)
showTags(tt)
```

But after I run my code, it threw me an importError: 

> Traceback (most recent call last):
  File "/Users/myname/Desktop/kytea_test/test.py", line 1, in <module>
    import Mykytea
  File "/Users/myname/Library/Python/3.8/lib/python/site-packages/Mykytea.py", line 15, in <module>
    import _Mykytea
ImportError: dlopen(/Users/myname/Library/Python/3.8/lib/python/site-packages/_Mykytea.cpython-38-darwin.so, 2): Symbol not found: __ZN5kytea10StringUtil9normalizeERKNS_11KyteaStringE
  Referenced from: /Users/myname/Library/Python/3.8/lib/python/site-packages/_Mykytea.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/myname/Library/Python/3.8/lib/python/site-packages/_Mykytea.cpython-38-darwin.so

I wonder if it's because my kytea was installed under /opt/homebrew/Cellar instead of /usr/local/lib, so I moved kytea folder to /usr/local/lib but it still threw me the importError.
I'm very new in using python and searched a lot for solving this but didn't find any solution. I would be very grateful if you can help me.

**Comment by chezou** [comment]
I guess you're trying to pip install via M1 macOS? If so, you need build Mykytea wheel by your own. See also https://github.com/chezou/Mykytea-python/pull/20

**Comment by lechang-zhang** [comment]
Yeah you are right. I'll try to build the wheel~
Thanks a lot.
